name: Fayez

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run_fayez:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Python
        run: python3 main.py
